#!/bin/bash

exec 2>&1

echo "Starting Apache Tomcat"

export JAVA_HOME=$(hab pkg path core/jdk8)
export TOMCAT_HOME="$(hab pkg path core/tomcat8)/tc"

{{#if bind.has_database ~}}
{{~#eachAlive bind.database.members as |member|}}
export CATALINA_OPTS="-DMONGODB_SERVICE_HOST={{member.sys.ip}} -DMONGODB_SERVICE_PORT={{member.cfg.port}}"
{{~/eachAlive}}
{{else ~}}
export CATALINA_OPTS="-DMONGODB_SERVICE_HOST={{cfg.mongodb_service_host}} -DMONGODB_SERVICE_PORT={{cfg.mongodb_service_port}}"
{{/if ~}}

cp {{pkg.path}}/*.war $TOMCAT_HOME/webapps

exec ${TOMCAT_HOME}/bin/catalina.sh run
