#!/bin/bash

exec 2>&1

echo "Starting Apache Tomcat"

export JAVA_HOME=$(hab pkg path core/jdk8)
export TOMCAT_HOME="$(hab pkg path core/tomcat8)/tc"

{{~#eachAlive bind.database.members as |member|}}
export CATALINA_OPTS="-DMONGODB_SERVICE_HOST={{member.sys.ip}} -DMONGODB_SERVICE_PORT={{member.cfg.port}}"
{{~/eachAlive}}

cp {{pkg.path}}/*.war $TOMCAT_HOME/webapps

exec ${TOMCAT_HOME}/bin/catalina.sh run
