version: '2'
services:
  mongodb:
    image: echohack/np-mongodb
    hostname: "mongodb"
    command: --strategy at-once
    environment:
      HAB_MONGODB: "[mongod.net]\nbind_ip = '0.0.0.0'\n[mongod.security]\ncluster_auth_mode = ''"
  national-parks:
    image: echohack/national-parks
    ports:
      - 8080:8080
      - 9631:9631
    links:
      - mongodb
    depends_on:
      - mongodb
    command: --strategy at-once --channel unstable --peer mongodb --bind database:np-mongodb.default
