maxconn = 32
httpchk = 'GET /national-parks'

[front-end]
listen = '*'
port = 8080
mode = 'http'

[status]
enabled = true
listen = '*'
port = 9000
user = 'admin'
password = 'password'
uri = '/haproxy-stats'